import type { Metadata } from "next";
import Link from "next/link";
import { BybitCostCalculator } from "@/components/BybitCostCalculator";
import { FAQList, homeFaqs } from "@/components/FAQList";
import { SectionHeader } from "@/components/Editorial";
import { SiteShell } from "@/components/SiteShell";
import { TrustNotice } from "@/components/TrustNotice";
import { HIGH_VOLUME_MAILTO, REBATE_APPLICATION_URL } from "@/config/links";
import { createPageMetadata } from "@/config/seo";
import { BIBECK_BASE_UPSTREAM_COMMISSION_RATE, calculateRebateFromEligibleFee, formatBibeckRebateRate } from "@/lib/bibeck-rebate";

export const metadata: Metadata = createPageMetadata({ title: "Bybit 交易成本、VIP 與 35% 返傭", description: "BiBeck Bybit 專區：計算交易成本、了解 VIP 費率與標準 35% 返傭，並申請符合資格的返傭帳戶。", path: "/bybit" });

const examples = [100, 1_000, 10_000].map((fee) => ({ fee, rebate: calculateRebateFromEligibleFee(fee) }));
const formatUsdt = (value: number) => `${value.toLocaleString("en-US")} USDT`;

export default function BybitPage() {
  return <SiteShell>
    <section className="home-hero relative px-5 pb-20 pt-36 sm:px-8 lg:pb-24 lg:pt-44"><div className="mx-auto grid min-h-[62vh] max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_0.95fr]"><div className="relative z-10 max-w-3xl"><p className="eyebrow">BYBIT COST OPTIMIZATION</p><h1 className="mt-7 text-balance text-5xl font-semibold leading-[1.06] text-white sm:text-7xl">先算清楚成本，再降低能降低的部分。</h1><p className="mt-7 max-w-2xl text-lg leading-9 text-secondary">BiBeck 提供 Bybit VIP 費率與交易成本試算，以及符合資格帳戶的標準 {formatBibeckRebateRate()} 返傭。</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/calculator" className="cta-button button-primary">計算交易成本</Link><Link href={REBATE_APPLICATION_URL} className="cta-button button-secondary">申請 {formatBibeckRebateRate()} 返傭</Link></div><p className="mt-6 text-xs leading-6 text-white/42">返傭不等於獲利，不應成為增加交易頻率或交易量的理由。實際資格與金額依 Bybit 與 BiBeck 紀錄為準。</p></div><div className="relative z-10 border border-gold/35 bg-[#14130e] p-6 sm:p-8"><p className="eyebrow">符合資格手續費</p><div className="mt-7 text-center"><strong className="font-mono text-3xl">1,000 USDT</strong><span className="my-4 block text-gold">×</span><strong className="font-mono text-5xl text-gold">35%</strong><span className="my-4 block text-gold">＝</span><strong className="font-mono text-3xl text-gold">350 USDT</strong></div></div></div></section>
    <section className="section-muted border-y border-white/10 px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="FEE TO REBATE" title="你的手續費，可以拿回多少？" copy="返傭基礎是符合資格的實際交易手續費，不是交易量。"/><div className="mt-10 grid gap-px bg-white/10 sm:grid-cols-3">{examples.map(({ fee, rebate }) => <article key={fee} className="bg-[#111] p-6"><p className="font-mono text-xl">{formatUsdt(fee)} 手續費</p><p className="my-4 text-gold" aria-hidden="true">↓</p><p className="font-mono text-3xl font-semibold text-gold">{formatUsdt(rebate)}</p><p className="mt-2 text-xs text-white/48">標準返傭試算</p></article>)}</div></div></section>
    <section className="border-y border-white/10 px-5 py-20 sm:px-8" id="trading-cost-calculator"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="TRADING COST" title="使用你的交易量計算 Bybit 實際成本" copy="比較一般費率、VIP 與 35% 返傭後的差異；計算結果是成本估算，不是報酬預測。"/><div className="mt-10"><BybitCostCalculator compact/></div></div></section>
    <section className="section-muted border-y border-white/10 px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="收入透明" title="BiBeck 怎麼賺錢？" copy="BiBeck 不靠喊單、帶單或投資建議向交易者收費。"/><div className="mt-10 grid gap-px bg-white/10 sm:grid-cols-3"><article className="bg-[#111] p-7"><p className="text-sm text-secondary">代理端返傭分潤</p><strong className="mt-3 block font-mono text-4xl">{BIBECK_BASE_UPSTREAM_COMMISSION_RATE * 100}%</strong></article><article className="bg-[#14130e] p-7"><p className="text-sm text-secondary">返還交易者</p><strong className="mt-3 block font-mono text-4xl text-gold">35%</strong></article><article className="bg-[#111] p-7"><p className="text-sm text-secondary">BiBeck 服務與營運收入</p><strong className="mt-3 block font-mono text-4xl">5%</strong></article></div><p className="mt-7 max-w-3xl text-sm leading-7 text-secondary">以目前基礎方案計算，BiBeck 將代理端取得返傭的 87.5% 返還給實際產生符合資格交易手續費的客戶。</p></div></section>
    <section className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="標準返傭與個別評估" title="35% 是標準產品，高交易量需求個別確認。" copy="高交易量、VIP、Quant、Bot、做市或特殊合作條件依真實交易結構個別評估，不會因填入交易量自動升級。"/><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={REBATE_APPLICATION_URL} className="cta-button button-primary">申請 35% 返傭</Link><a href={HIGH_VOLUME_MAILTO} target="_blank" rel="noopener noreferrer" className="cta-button button-secondary">洽談高交易量方案</a></div></div></section>
    <section className="section-muted border-y border-white/10 px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="數字可核對" title="不用相信我們，直接核對數字。" copy="費率、資格、返傭紀錄與收入分配，都應該能被說明與查證。"/><div className="mt-8"><TrustNotice/></div></div></section>
    <section className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="開始申請" title="三步完成 Bybit 35% 返傭申請。"/><ol className="mt-10 grid gap-px bg-white/10 md:grid-cols-3">{[["01","建立符合 BiBeck 推薦關係的 Bybit 帳戶"],["02","在 BiBeck 官網提交 UID 與基本資料"],["03","完成開通後，以符合資格帳戶交易並取得返傭"]].map(([number,title]) => <li key={number} className="bg-[#111] p-7"><span className="font-mono text-gold">{number}</span><h3 className="mt-5 text-xl font-semibold leading-8">{title}</h3></li>)}</ol><Link href={REBATE_APPLICATION_URL} className="cta-button button-primary mt-8">申請 35% 返傭</Link></div></section>
    <section className="border-y border-white/10 px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.7fr_1.3fr]"><SectionHeader eyebrow="常見問題" title="先把重要問題說清楚。" copy="透明的資格與風險界線，是返傭服務建立信任的第一步。"/><div><FAQList items={homeFaqs}/><Link href="/faq" className="text-link mt-8">查看所有問題 <span aria-hidden="true">→</span></Link></div></div></section>
  </SiteShell>;
}
