export type FreezeDisposition = "BLOCKS_FREEZE" | "RESEARCH_REQUIRED" | "SAFETY_PROPERTY";
export interface AdversarialCase { id:string; whyExistingSuiteWasInsufficient:string; scenario:string; axis:string[]; ruleIds:string[]; findingIds:string[]; expectedSafetyProperty:string; forbiddenOutputs:string[]; disposition:FreezeDisposition }

export const adversarialCases: AdversarialCase[] = [
  { id:"ADV-001",whyExistingSuiteWasInsufficient:"CASE-024 只抓重複 assignment ID，抓不到同一銀行現金被建立成兩個不同 Resource。",scenario:"同一筆十萬元活存同時被正規化為營運資金十萬元與安全資金十萬元。",axis:["DOUBLE_COUNTING","RESOURCE_LINEAGE"],ruleIds:["R-008"],findingIds:["AUD-B003"],expectedSafetyProperty:"來源資產的所有 resource partition 合計不得超過來源價值。",forbiddenOutputs:["不得顯示可用資源為二十萬元"],disposition:"BLOCKS_FREEZE" },
  { id:"ADV-002",whyExistingSuiteWasInsufficient:"既有目標案例未連結 Goal.currentFunding 與 Asset/Resource。",scenario:"購屋目標 currentFunding 六十萬元與 GOAL asset 六十萬元其實是同一筆錢。",axis:["DOUBLE_COUNTING","GOAL_FUNDING"],ruleIds:["R-008"],findingIds:["AUD-B003"],expectedSafetyProperty:"目標已備資金與資產必須共享來源血統。",forbiddenOutputs:["不得把同一筆六十萬元計為一百二十萬元"],disposition:"BLOCKS_FREEZE" },
  { id:"ADV-003",whyExistingSuiteWasInsufficient:"既有現金流案例未處理債務最低還款同時出現在 obligation。",scenario:"信用卡最低還款同時列入 Liability.minimumMonthlyPayment 與 30 日 Obligation。",axis:["DOUBLE_COUNTING","CASH_FLOW"],ruleIds:["R-008"],findingIds:["AUD-B004"],expectedSafetyProperty:"同一付款事件只能進入核心流出一次。",forbiddenOutputs:["不得重複扣除最低還款"],disposition:"BLOCKS_FREEZE" },
  { id:"ADV-004",whyExistingSuiteWasInsufficient:"沒有測試收入與 FUTURE_INCOME resource 的期間重疊。",scenario:"本月薪資同時被算入 NetMonthlyIncome 與可立即動用的 FUTURE_INCOME。",axis:["DOUBLE_COUNTING","TIME_BASIS"],ruleIds:["R-008"],findingIds:["AUD-B003"],expectedSafetyProperty:"收入事件與資源可用日期必須有唯一時間與來源。",forbiddenOutputs:["不得在同一期間重複增加現金與收入"],disposition:"BLOCKS_FREEZE" },
  { id:"ADV-005",whyExistingSuiteWasInsufficient:"沒有共同持有或需他人同意的資源。",scenario:"共同帳戶有一百萬元，但使用者只能單獨動用其中部分且比例未知。",axis:["OWNERSHIP","RESTRICTION","MISSING_DATA"],ruleIds:[],findingIds:["AUD-B003"],expectedSafetyProperty:"未知可動用比例時不得把全額視為 owned available capital。",forbiddenOutputs:["不得把全額列為高信心安全流動性"],disposition:"BLOCKS_FREEZE" },
  { id:"ADV-006",whyExistingSuiteWasInsufficient:"CASE-019 只有集中度，未處理結算、波動與出售成本。",scenario:"加密資產可即時交易，但價格劇烈波動且提領受限；股票尚未交割。",axis:["LIQUIDITY","VALUATION","SETTLEMENT"],ruleIds:[],findingIds:["AUD-B003","AUD-R003"],expectedSafetyProperty:"技術上可交易不得直接等同可安全動用。",forbiddenOutputs:["不得把全部市值列為立即安全流動性"],disposition:"RESEARCH_REQUIRED" },
  { id:"ADV-007",whyExistingSuiteWasInsufficient:"CASE-020 只有一種零收入情境。",scenario:"退休者沒有勞務收入，以可持續提款支付生活且近期義務已備妥。",axis:["ZERO_INCOME","RUNWAY","WITHDRAWAL"],ruleIds:["R-013"],findingIds:[],expectedSafetyProperty:"收入為零不得自動判定 SURVIVAL；應評估提款現金流與資源覆蓋。",forbiddenOutputs:["不得只因收入為零產生危急警告"],disposition:"SAFETY_PROPERTY" },
  { id:"ADV-008",whyExistingSuiteWasInsufficient:"CASE-010 只有 APR 完全未知，沒有促銷到期。",scenario:"信用卡目前 0% APR，三個月後轉為未知浮動利率。",axis:["DEBT","TIME_VARYING_RATE","MISSING_DATA"],ruleIds:["R-006"],findingIds:["AUD-M005"],expectedSafetyProperty:"不得以目前 0% 永久化推論債務優先。",forbiddenOutputs:["不得宣稱此債務沒有成本","不得用未知未來利率做確定比較"],disposition:"BLOCKS_FREEZE" },
  { id:"ADV-009",whyExistingSuiteWasInsufficient:"COLLISION-002 沒有提前清償成本與還款後流動性衝擊。",scenario:"提前還款會產生違約金，且一次還款將使 30 日必要義務無法支付。",axis:["DEBT","LIQUIDITY","PREPAYMENT"],ruleIds:["R-005","R-006"],findingIds:["AUD-B005","AUD-M005","AUD-R002"],expectedSafetyProperty:"債務加速不得破壞近期必要義務資金。",forbiddenOutputs:["不得只比較 APR 與預期投資報酬","不得讓可用現金降至必要義務以下"],disposition:"BLOCKS_FREEZE" },
  { id:"ADV-010",whyExistingSuiteWasInsufficient:"既有目標都有 targetAmount 與 targetDate。",scenario:"使用者有重要目標，但金額與期限都尚未確定。",axis:["GOAL","MISSING_DATA"],ruleIds:["R-001"],findingIds:["AUD-B004"],expectedSafetyProperty:"建立 DISCOVER 任務，不得推導所需報酬。",forbiddenOutputs:["不得用更高投資風險補足未知目標","不得猜測金額或期限"],disposition:"BLOCKS_FREEZE" },
  { id:"ADV-011",whyExistingSuiteWasInsufficient:"CASE-002 沒有極端財富但低流動性。",scenario:"使用者淨值極高但全為不動產，十天後有大型必要醫療支出。",axis:["ILLIQUID_WEALTH","NEAR_TERM_OBLIGATION","STAGE_SEVERITY"],ruleIds:["R-004","R-005"],findingIds:["AUD-M003","AUD-R002"],expectedSafetyProperty:"高淨值不得掩蓋近期資金缺口。",forbiddenOutputs:["不得因淨值高而判定 OPTIONALITY","不得把不動產全額視為 30 日流動性"],disposition:"SAFETY_PROPERTY" },
  { id:"ADV-012",whyExistingSuiteWasInsufficient:"CASE-011 高收入仍有正剩餘，未測極端收入搭配負現金流。",scenario:"月收入五十萬元，但必要與承諾支出合計六十萬元。",axis:["HIGH_INCOME","NEGATIVE_CASH_FLOW","STAGE_SEVERITY"],ruleIds:["R-003"],findingIds:["AUD-M003"],expectedSafetyProperty:"高收入不得掩蓋負核心現金流。",forbiddenOutputs:["不得因收入高而進入 GROWTH"],disposition:"SAFETY_PROPERTY" },
  { id:"ADV-013",whyExistingSuiteWasInsufficient:"既有 suite 沒有同時觸發多個 stage 的規則排序案例。",scenario:"同時存在逾期、30 日資金缺口、負核心現金流與必要目標缺口。",axis:["RULE_ORDER","MULTIPLE_STAGE","MISSION_VERIFICATION"],ruleIds:[],findingIds:["AUD-B001","AUD-B002","AUD-B005","AUD-M003","AUD-M004"],expectedSafetyProperty:"必須以顯式 override/tie-break 決定單一主要瓶頸，且保留其他未解決 claims。",forbiddenOutputs:["不得依 registry 陣列順序偶然選擇","不得以任意加權總分掩蓋衝突"],disposition:"BLOCKS_FREEZE" },
  { id:"ADV-014",whyExistingSuiteWasInsufficient:"CASE-013 只有平均變動收入，沒有年度支出與季節性期間。",scenario:"季節性接案收入集中於上半年，年度保費與所得稅集中於下半年。",axis:["IRREGULAR_INCOME","ANNUAL_EXPENSE","TIME_BASIS"],ruleIds:["R-001","R-003"],findingIds:["AUD-B004","AUD-M001","AUD-R001"],expectedSafetyProperty:"不得用單月平均值製造全年穩定假象。",forbiddenOutputs:["不得給出高信心固定月剩餘","不得忽略已知年度義務"],disposition:"RESEARCH_REQUIRED" },
  { id:"ADV-015",whyExistingSuiteWasInsufficient:"CASE-017 未明確測高可支配消費且所有高優先主張已完成。",scenario:"使用者娛樂支出高，但必要義務、安全資金與自行選擇的目標均已備妥。",axis:["DISCRETIONARY_NEUTRALITY","NO_MISSION"],ruleIds:["R-011","R-014"],findingIds:["AUD-A002"],expectedSafetyProperty:"不得把娛樂支出本身視為錯誤或製造任務。",forbiddenOutputs:["不得使用浪費、不自律等道德評語","不得強行產生減少娛樂任務"],disposition:"SAFETY_PROPERTY" },
];
