import { createContext, flag, scalar } from "../reference/context-builder.ts";
import type { NormalizedDecisionContext, Severity, Stage } from "../schemas/index.ts";
const base=()=>createContext({"flags.hasMissingCriticalData":flag(false),"flags.hasDelinquentDebt":flag(false),"flags.hasImmediateFundingGap":flag(false),"flags.hasNegativeCoreCashFlow":flag(false),"flags.hasUnknownDebtCost":flag(false),"flags.hasHighCostDebt":flag(false),"flags.hasMinimumViableLiquidityGap":flag(false),"flags.hasCapitalAssignmentConflict":flag(false),"flags.hasReservedCapital":flag(false),"flags.hasGoalConflict":flag(false),"flags.hasGoalFundingClaim":flag(false),"flags.hasAllocationConflict":flag(false),"flags.hasNegativeNetWorth":flag(false),"flags.hasZeroIncome":flag(false),"flags.hasCashFlowContradiction":flag(false),"flags.hasUnresolvedPriorityClaim":flag(true),"counts.unresolvedPriorityClaims":scalar(1)});
export interface ExecutableExpected { matchedRuleIds:string[]; stage:Stage|null; severity:Severity; bottleneckCode:string|null; mainQuestCode:string|null; halted:boolean; confidence:"HIGH"|"MEDIUM"|"LOW"|"EXPERIMENTAL" }
export interface ExecutableCase { id:string; rationale:string; context:NormalizedDecisionContext; expected:ExecutableExpected }
const make=(id:string,rationale:string,overrides:Parameters<typeof createContext>[0],expected:ExecutableExpected):ExecutableCase=>({id,rationale,context:Object.assign(base(),overrides),expected});
export const executableCases:ExecutableCase[]=[
  make("EXEC-001","缺漏不相關資料不能抹除有獨立已知逾期依據的修復；Discover 保留為次要任務。",{"flags.hasMissingCriticalData":flag(true),"flags.hasDelinquentDebt":flag(true)},{matchedRuleIds:["R-001","R-002"],stage:"SURVIVAL",severity:"CRITICAL",bottleneckCode:"DELINQUENT_DEBT",mainQuestCode:"RESOLVE_DELINQUENCY",halted:false,confidence:"HIGH"}),
  make("EXEC-002","資本超額配置是 critical halt。",{"flags.hasCapitalAssignmentConflict":flag(true),"flags.hasNegativeCoreCashFlow":flag(true)},{matchedRuleIds:["R-008"],stage:null,severity:"HIGH",bottleneckCode:"CAPITAL_ASSIGNMENT_CONFLICT",mainQuestCode:null,halted:true,confidence:"HIGH"}),
  make("EXEC-003","現金流資料矛盾阻止下游結論。",{"flags.hasCashFlowContradiction":flag(true),"flags.hasGoalConflict":flag(true)},{matchedRuleIds:["R-015"],stage:"STABILITY",severity:"MEDIUM",bottleneckCode:"CASH_FLOW_CONTRADICTION",mainQuestCode:"RECONCILE_CASH_FLOW_INPUTS",halted:true,confidence:"HIGH"}),
  make("EXEC-004","重大逾期明確壓過 Goal/Growth 類候選。",{"flags.hasDelinquentDebt":flag(true),"flags.hasGoalConflict":flag(true),"flags.hasGoalFundingClaim":flag(true)},{matchedRuleIds:["R-002","R-010","R-009"],stage:"SURVIVAL",severity:"CRITICAL",bottleneckCode:"DELINQUENT_DEBT",mainQuestCode:"RESOLVE_DELINQUENCY",halted:false,confidence:"MEDIUM"}),
  make("EXEC-005","負核心現金流與近期缺口同時存在時依 phase/order 決定 primary，severity 獨立取最高。",{"flags.hasNegativeCoreCashFlow":flag(true),"flags.hasImmediateFundingGap":flag(true)},{matchedRuleIds:["R-003","R-004"],stage:"SURVIVAL",severity:"CRITICAL",bottleneckCode:"NEGATIVE_CORE_CASH_FLOW",mainQuestCode:"REPAIR_CORE_CASH_FLOW",halted:false,confidence:"HIGH"}),
  make("EXEC-006","只有近期資金缺口時產生明確修復任務。",{"flags.hasImmediateFundingGap":flag(true)},{matchedRuleIds:["R-004"],stage:"SURVIVAL",severity:"HIGH",bottleneckCode:"IMMEDIATE_FUNDING_GAP",mainQuestCode:"CLOSE_IMMEDIATE_FUNDING_GAP",halted:false,confidence:"HIGH"}),
  make("EXEC-007","保留資本只形成 side finding，不單獨製造 primary。",{"flags.hasReservedCapital":flag(true)},{matchedRuleIds:["R-007"],stage:null,severity:"MEDIUM",bottleneckCode:null,mainQuestCode:null,halted:false,confidence:"HIGH"}),
  make("EXEC-008","高成本債務與最低流動性缺口同時存在時先建立最低流動性。",{"flags.hasHighCostDebt":flag(true),"flags.hasMinimumViableLiquidityGap":flag(true)},{matchedRuleIds:["R-005"],stage:"STABILITY",severity:"HIGH",bottleneckCode:"MINIMUM_LIQUIDITY_GAP",mainQuestCode:"BUILD_MINIMUM_LIQUIDITY",halted:false,confidence:"LOW"}),
  make("EXEC-009","流動性里程碑已達且成本分類已知時才啟動債務優先。",{"flags.hasHighCostDebt":flag(true),"flags.hasMinimumViableLiquidityGap":flag(false),"flags.hasUnknownDebtCost":flag(false)},{matchedRuleIds:["R-006"],stage:"CONTROL",severity:"HIGH",bottleneckCode:"HIGH_COST_DEBT",mainQuestCode:"REDUCE_HIGH_COST_DEBT",halted:false,confidence:"LOW"}),
  make("EXEC-010","未知債務成本產生 Discover，不得觸發確定性高成本債務結論。",{"flags.hasHighCostDebt":flag(true),"flags.hasUnknownDebtCost":flag(true)},{matchedRuleIds:["R-006"],stage:"CONTROL",severity:"MEDIUM",bottleneckCode:"NEED_MORE_INFORMATION",mainQuestCode:"CONFIRM_DEBT_COST",halted:true,confidence:"LOW"}),
  make("EXEC-011","可支配支出只有在資源配置衝突時產生 DECIDE。",{"flags.hasAllocationConflict":flag(true)},{matchedRuleIds:["R-011"],stage:"CONTROL",severity:"MEDIUM",bottleneckCode:"ALLOCATION_CONFLICT",mainQuestCode:"DECIDE_ALLOCATION_TRADEOFF",halted:false,confidence:"MEDIUM"}),
  make("EXEC-012","負淨值在無其他高優先問題時只形成 context finding。",{"flags.hasNegativeNetWorth":flag(true)},{matchedRuleIds:["R-012"],stage:null,severity:"LOW",bottleneckCode:null,mainQuestCode:null,halted:false,confidence:"HIGH"}),
  make("EXEC-013","零收入只觸發資源覆蓋檢查，不自動判定 SURVIVAL。",{"flags.hasZeroIncome":flag(true)},{matchedRuleIds:["R-013"],stage:null,severity:"MEDIUM",bottleneckCode:null,mainQuestCode:null,halted:false,confidence:"HIGH"}),
  make("EXEC-014","目標衝突與目標資金排擠投資同時保留，但衝突是 primary。",{"flags.hasGoalConflict":flag(true),"flags.hasGoalFundingClaim":flag(true)},{matchedRuleIds:["R-010","R-009"],stage:"ACCUMULATION",severity:"MEDIUM",bottleneckCode:"GOAL_FUNDING_CONFLICT",mainQuestCode:"DECIDE_GOAL_PRIORITY",halted:false,confidence:"MEDIUM"}),
  make("EXEC-015","只有目標資金主張時不得自動製造另一個主要任務。",{"flags.hasGoalFundingClaim":flag(true)},{matchedRuleIds:["R-009"],stage:null,severity:"MEDIUM",bottleneckCode:null,mainQuestCode:null,halted:false,confidence:"MEDIUM"}),
  make("EXEC-016","沒有未解決主張時不強制任務，也不得由此推定未凍結的 OPTIONALITY。",{"flags.hasUnresolvedPriorityClaim":flag(false),"counts.unresolvedPriorityClaims":scalar(0)},{matchedRuleIds:["R-014"],stage:null,severity:"NONE",bottleneckCode:"NO_UNRESOLVED_PRIORITY_CLAIM",mainQuestCode:null,halted:false,confidence:"HIGH"}),
];
