import { known, unknown, type FinancialClaim, type FinancialProfile, type FinancialResource, type ResourceAllocation, type Severity, type Stage } from "../schemas/index.ts";

const dp = <T>(value:T) => ({ value, source:"USER_REPORTED" as const, updatedAt:"2026-09-30" });
const profile = (overrides:Partial<FinancialProfile> = {}): FinancialProfile => ({
  profile:{ primaryCurrency:"TWD", country:"TW" },
  income:[{ id:"income-1", type:"SALARY", averageMonthlyNetIncome:dp(60000), stability:"HIGH" }],
  expenses:{ necessaryMonthly:dp(30000), discretionaryMonthly:dp(10000), otherMonthlyRequired:dp(0) },
  assets:[{ id:"asset-cash", type:"CASH", currentValue:dp(180000), liquidity:"IMMEDIATE", purpose:"SAFETY" }],
  liabilities:[], obligations:[], goals:[], household:{ dependents:dp(0), externalSupportAvailable:dp(false) }, ...overrides,
});
const resource = (amount=180000, purpose:"SAFETY"|"GOAL"|"LONG_TERM"|"EXPERIMENTAL"="SAFETY"):FinancialResource => ({ id:`resource-${purpose.toLowerCase()}`,type:purpose === "GOAL"?"GOAL_CAPITAL":purpose === "LONG_TERM"?"LONG_TERM_CAPITAL":"CURRENT_CASH",amount:known(amount),underlyingAssetId:"asset-cash",ownership:"SOLE",availability:purpose === "GOAL"?"RESERVED":"AVAILABLE",liquidity:"IMMEDIATE",valuationStatus:"KNOWN",purpose,availableFrom:known("2026-09-30"),reservedForClaimIds:[],source:"USER_REPORTED",certainty:purpose === "LONG_TERM"?"MEDIUM":"HIGH" });
const claim = (id:string,claimType:FinancialClaim["claimType"],category:FinancialClaim["category"],amount:number):FinancialClaim => {
  const debt=["DEBT_ACCELERATION","DEBT_MINIMUM","DELINQUENT_DEBT"].includes(claimType);
  const assignment=claimType==="SAFETY_BUFFER"||claimType==="GOAL_FUNDING";
  return {id,claimType,category,amount:known(amount),dueDate:unknown("DUE_DATE_NOT_PROVIDED"),required:category==="HARD",userPriority:"MEDIUM",urgency:category==="HARD"?"IMMEDIATE":"LATER",severity:category==="HARD"?"HIGH":"MEDIUM",certainty:"HIGH",reversibility:"MEDIUM",lifecycleStatus:"ACTIVE",fundedAmount:known(0),fundingStatus:"UNFUNDED",eligibleResources:["resource-safety"],stageImpact:category==="HARD"?"SURVIVAL":"ACCUMULATION",source:"USER_REPORTED",modelVersion:"1.0.0",origin:{type:"USER_INPUT"},recurrence:"NONE",
    ...(debt?{debtPayment:{liabilityId:id,principal:unknown<number>("SYNTHETIC_BREAKDOWN_NOT_PROVIDED"),interest:unknown<number>("SYNTHETIC_BREAKDOWN_NOT_PROVIDED"),fees:unknown<number>("SYNTHETIC_BREAKDOWN_NOT_PROVIDED")}}:{}),
    fulfillmentEffects:debt?[{code:"REDUCE_CASH",amountSource:"CLAIM_AMOUNT"},{code:"REDUCE_DEBT_BALANCE",targetId:id,amountSource:"DEBT_PRINCIPAL"}]:assignment?[{code:claimType==="SAFETY_BUFFER"?"INCREASE_SAFETY_CAPITAL":"FUND_GOAL",targetId:id,amountSource:"FUNDED_AMOUNT",assignmentOnly:true}]:[{code:"REDUCE_CASH",targetId:id,amountSource:"FUNDED_AMOUNT"}],
  };
};

export interface FixtureExpected { stage:Stage; severity:Severity; primaryBottleneck:string; prioritizedClaims:string[]; allowedMainQuests:string[]; requiredFlags:string[]; forbiddenAllocations:string[]; forbiddenOutputs:string[]; resourceInvariant:boolean; claimInvariant:boolean }
export interface MoneyModelFixture { id:string; description:string; inputProfile:FinancialProfile; resources:FinancialResource[]; claims:FinancialClaim[]; allocations?:ResourceAllocation[]; ruleIds:string[]; expected:FixtureExpected }
export const syntheticSuiteMetadata = { validationLevel:"STRUCTURE_ONLY" as const, requiresReferenceEvaluator:true };
const expected = (stage:Stage,severity:Severity,bottleneck:string, ruleFlag:string, quest:string|null="DISCOVER"):FixtureExpected => ({ stage,severity,primaryBottleneck:bottleneck,prioritizedClaims:[],allowedMainQuests:quest?[quest]:[],requiredFlags:[ruleFlag],forbiddenAllocations:["不得使用未具資格或已保留的資源"],forbiddenOutputs:["不得猜測缺漏資料","不得產生未受規則支持的資產推薦"],resourceInvariant:true,claimInvariant:true });

export const syntheticCases: MoneyModelFixture[] = [
  { id:"CASE-001",description:"核心現金流為負",inputProfile:profile({ income:[{id:"income-1",type:"SALARY",averageMonthlyNetIncome:dp(30000),stability:"HIGH"}],expenses:{necessaryMonthly:dp(40000),discretionaryMonthly:dp(0)} }),resources:[resource(10000)],claims:[claim("living","NECESSARY_LIVING","HARD",40000)],ruleIds:["R-003"],expected:expected("SURVIVAL","CRITICAL","核心現金流不足","NEGATIVE_CORE_CASH_FLOW","REPAIR") },
  { id:"CASE-002",description:"資產多但 30 日必要義務有缺口",inputProfile:profile({ obligations:[{id:"rent",name:"房租",amount:dp(80000),dueDate:"2026-10-05",required:true,reservedAmount:dp(0)}] }),resources:[resource(20000),resource(1000000,"LONG_TERM")],claims:[claim("rent","IMMEDIATE_OBLIGATION","HARD",80000)],ruleIds:["R-004"],expected:expected("SURVIVAL","HIGH","近期必要資金缺口","IMMEDIATE_FUNDING_GAP","BUILD") },
  { id:"CASE-003",description:"信用卡已逾期",inputProfile:profile({ liabilities:[{id:"card",type:"CREDIT_CARD",balance:dp(90000),minimumMonthlyPayment:dp(5000),secured:false,delinquencyStatus:"DELINQUENT"}] }),resources:[resource(60000)],claims:[claim("late-card","DELINQUENT_DEBT","HARD",90000)],ruleIds:["R-002"],expected:expected("SURVIVAL","CRITICAL","重大逾期","RESOLVE_DELINQUENCY","REPAIR") },
  { id:"CASE-004",description:"高收入但現金很少",inputProfile:profile({ income:[{id:"income-1",type:"SALARY",averageMonthlyNetIncome:dp(200000),stability:"HIGH"}],assets:[{id:"cash",type:"CASH",currentValue:dp(5000),liquidity:"IMMEDIATE",purpose:"OPERATING"}],obligations:[{id:"tax",name:"必要稅款",amount:dp(30000),dueDate:"2026-10-10",required:true,reservedAmount:dp(0)}] }),resources:[resource(5000)],claims:[claim("tax","IMMEDIATE_OBLIGATION","HARD",30000)],ruleIds:["R-004"],expected:expected("SURVIVAL","HIGH","近期必要資金缺口","IMMEDIATE_FUNDING_GAP","BUILD") },
  { id:"CASE-005",description:"現金已保留給必要支出",inputProfile:profile({ obligations:[{id:"medical",name:"醫療費",amount:dp(100000),dueDate:"2026-10-15",required:true,reservedAmount:dp(100000)}] }),resources:[resource(180000)],claims:[claim("medical","IMMEDIATE_OBLIGATION","HARD",100000)],ruleIds:["R-007"],expected:expected("STABILITY","MEDIUM","可用安全流動性低於帳面現金","EXCLUDE_RESERVED_CAPITAL",null) },
  { id:"CASE-006",description:"單一變動收入且有扶養人",inputProfile:profile({ income:[{id:"income-1",type:"COMMISSION",averageMonthlyNetIncome:dp(90000),stability:"LOW"}],household:{dependents:dp(2),externalSupportAvailable:dp(false)} }),resources:[resource(40000)],claims:[claim("buffer","SAFETY_BUFFER","PROTECTIVE",90000)],ruleIds:["R-001"],expected:expected("STABILITY","MEDIUM","收入風險資訊仍不足","NEED_MORE_INFORMATION","DISCOVER") },
  { id:"CASE-007",description:"高成本債務且流動性足夠",inputProfile:profile({ liabilities:[{id:"card",type:"CREDIT_CARD",balance:dp(120000),apr:dp(18),minimumMonthlyPayment:dp(6000),secured:false,delinquencyStatus:"CURRENT"}] }),resources:[resource(240000)],claims:[claim("debt","DEBT_ACCELERATION","PROTECTIVE",120000)],ruleIds:["R-006"],expected:expected("CONTROL","HIGH","高成本債務","DEBT_PRIORITY","REPAIR") },
  { id:"CASE-008",description:"高成本債務但流動性不足",inputProfile:profile({ liabilities:[{id:"card",type:"CREDIT_CARD",balance:dp(120000),apr:dp(18),minimumMonthlyPayment:dp(6000),secured:false,delinquencyStatus:"CURRENT"}] }),resources:[resource(10000)],claims:[claim("buffer","SAFETY_BUFFER","PROTECTIVE",30000),claim("debt","DEBT_ACCELERATION","PROTECTIVE",120000)],ruleIds:["R-005"],expected:expected("STABILITY","HIGH","最低可行流動性不足","BUILD_MINIMUM_LIQUIDITY","BUILD") },
  { id:"CASE-009",description:"大型低成本房貸造成負淨值，但現金流與最低還款正常",inputProfile:profile({ assets:[{id:"cash",type:"CASH",currentValue:dp(3000000),liquidity:"IMMEDIATE",purpose:"SAFETY"}],liabilities:[{id:"mortgage",type:"MORTGAGE",balance:dp(8000000),apr:dp(2),minimumMonthlyPayment:dp(30000),secured:true,delinquencyStatus:"CURRENT"}] }),resources:[resource(300000)],claims:[claim("mortgage","DEBT_MINIMUM","HARD",30000)],ruleIds:["R-012"],expected:expected("CONTROL","LOW","負淨值不單獨形成危急瓶頸","DO_NOT_ESCALATE_FROM_NET_WORTH_ALONE",null) },
  { id:"CASE-010",description:"貸款 APR 未知",inputProfile:profile({ liabilities:[{id:"loan",type:"PERSONAL_LOAN",balance:dp(300000),minimumMonthlyPayment:dp(9000),secured:false,delinquencyStatus:"CURRENT"}] }),resources:[resource()],claims:[claim("loan","DEBT_ACCELERATION","PROTECTIVE",300000)],ruleIds:["R-001"],expected:expected("STABILITY","MEDIUM","債務成本資料不足","NEED_MORE_INFORMATION","DISCOVER") },
  { id:"CASE-011",description:"高收入但資本形成偏低",inputProfile:profile({ income:[{id:"income-1",type:"SALARY",averageMonthlyNetIncome:dp(180000),stability:"HIGH"}],expenses:{necessaryMonthly:dp(60000),discretionaryMonthly:dp(110000)} }),resources:[resource(20000)],claims:[claim("capital","LONG_TERM_GROWTH","CHOSEN",30000)],ruleIds:["R-011"],expected:expected("CONTROL","MEDIUM","資金配置衝突","ALLOCATION_CONFLICT","DECIDE") },
  { id:"CASE-012",description:"收入較低但剩餘穩定",inputProfile:profile({ income:[{id:"income-1",type:"SALARY",averageMonthlyNetIncome:dp(50000),stability:"HIGH"}],expenses:{necessaryMonthly:dp(22000),discretionaryMonthly:dp(5000)} }),resources:[resource(150000)],claims:[],ruleIds:["R-014"],expected:expected("OPTIONALITY","NONE","目前沒有未解決的優先主張","NO_FORCED_MISSION",null) },
  { id:"CASE-013",description:"收入高度波動",inputProfile:profile({ income:[{id:"income-1",type:"FREELANCE",averageMonthlyNetIncome:dp(80000),stability:"LOW"}] }),resources:[resource(60000)],claims:[claim("buffer","SAFETY_BUFFER","PROTECTIVE",90000)],ruleIds:["R-001"],expected:expected("STABILITY","MEDIUM","收入波動所需資訊不足","NEED_MORE_INFORMATION","DISCOVER") },
  { id:"CASE-014",description:"近期購屋必要目標",inputProfile:profile({ goals:[{id:"house",name:"購屋自備款",targetAmount:dp(1000000),currentFunding:dp(600000),targetDate:"2027-03-01",priority:"HIGH",required:true}] }),resources:[resource(600000,"GOAL"),resource(200000,"LONG_TERM")],claims:[claim("house","GOAL_FUNDING","CHOSEN",400000)],ruleIds:["R-009"],expected:expected("ACCUMULATION","MEDIUM","目標資金與長期配置競爭","REDUCE_LONG_TERM_INVESTABLE_CAPITAL","DECIDE") },
  { id:"CASE-015",description:"目標金額與期限不可行",inputProfile:profile({ goals:[{id:"goal",name:"一年內準備高額資金",targetAmount:dp(3000000),currentFunding:dp(0),targetDate:"2027-09-30",priority:"HIGH",required:false}] }),resources:[resource(20000)],claims:[claim("goal","GOAL_FUNDING","CHOSEN",3000000)],ruleIds:["R-010"],expected:expected("ACCUMULATION","MEDIUM","資金需求衝突","FUNDING_CONFLICT","DECIDE") },
  { id:"CASE-016",description:"多個目標競爭同一資金",inputProfile:profile({ goals:[{id:"home",name:"住屋",targetAmount:dp(800000),currentFunding:dp(200000),targetDate:"2027-12-31",priority:"HIGH",required:true},{id:"travel",name:"旅行",targetAmount:dp(150000),currentFunding:dp(0),targetDate:"2027-03-01",priority:"HIGH",required:false}] }),resources:[resource(250000,"GOAL")],claims:[claim("home","GOAL_FUNDING","CHOSEN",600000),claim("travel","GOAL_FUNDING","CHOSEN",150000)],ruleIds:["R-010"],expected:expected("ACCUMULATION","MEDIUM","多個目標的資金需求衝突","FUNDING_CONFLICT","DECIDE") },
  { id:"CASE-017",description:"健康狀態且沒有急迫任務",inputProfile:profile(),resources:[resource()],claims:[],ruleIds:["R-014"],expected:expected("OPTIONALITY","NONE","目前沒有未解決的優先主張","NO_FORCED_MISSION",null) },
  { id:"CASE-018",description:"高資產且不製造假問題",inputProfile:profile({ assets:[{id:"cash",type:"CASH",currentValue:dp(10000000),liquidity:"IMMEDIATE",purpose:"SAFETY"}] }),resources:[resource(10000000)],claims:[],ruleIds:["R-014"],expected:expected("OPTIONALITY","NONE","目前沒有未解決的優先主張","NO_FORCED_MISSION",null) },
  { id:"CASE-019",description:"加密資產高度集中",inputProfile:profile({ assets:[{id:"crypto",type:"CRYPTO",currentValue:dp(3000000),liquidity:"SHORT",purpose:"LONG_TERM"},{id:"cash",type:"CASH",currentValue:dp(100000),liquidity:"IMMEDIATE",purpose:"SAFETY"}] }),resources:[resource(100000),resource(3000000,"LONG_TERM")],claims:[],ruleIds:["R-001"],expected:expected("STABILITY","MEDIUM","風險限制資料不足","NEED_MORE_INFORMATION","DISCOVER") },
  { id:"CASE-020",description:"零收入但有大量流動資源",inputProfile:profile({ income:[],assets:[{id:"cash",type:"CASH",currentValue:dp(3000000),liquidity:"IMMEDIATE",purpose:"SAFETY"}] }),resources:[resource(3000000)],claims:[],ruleIds:["R-013"],expected:expected("STABILITY","MEDIUM","需依續航與義務判斷","EVALUATE_RESOURCE_RUNWAY",null) },
  { id:"CASE-021",description:"負淨值但正在改善",inputProfile:profile({ liabilities:[{id:"loan",type:"STUDENT_LOAN",balance:dp(1000000),apr:dp(2),minimumMonthlyPayment:dp(10000),secured:false,delinquencyStatus:"CURRENT"}] }),resources:[resource(200000)],claims:[claim("minimum","DEBT_MINIMUM","HARD",10000)],ruleIds:["R-012"],expected:expected("CONTROL","LOW","負淨值本身不是危急條件","DO_NOT_ESCALATE_FROM_NET_WORTH_ALONE",null) },
  { id:"CASE-022",description:"必要支出未知",inputProfile:profile({ expenses:{discretionaryMonthly:dp(10000)} }),resources:[resource()],claims:[],ruleIds:["R-001"],expected:expected("STABILITY","MEDIUM","必要支出資料不足","NEED_MORE_INFORMATION","DISCOVER") },
  { id:"CASE-023",description:"回報現金流互相矛盾",inputProfile:profile({ reportedMonthlySavings:dp(50000) }),resources:[resource()],claims:[],ruleIds:["R-015"],expected:expected("STABILITY","MEDIUM","現金流資料需要核對","NEED_MORE_INFORMATION","DISCOVER") },
  { id:"CASE-024",description:"同一資本被重複配置",inputProfile:profile(),resources:[resource(100000)],claims:[claim("goal","GOAL_FUNDING","CHOSEN",70000),claim("growth","LONG_TERM_GROWTH","CHOSEN",70000)],allocations:[{resourceId:"resource-safety",claimId:"goal",amount:70000,capitalAssignmentId:"A-1"},{resourceId:"resource-safety",claimId:"growth",amount:70000,capitalAssignmentId:"A-1"}],ruleIds:["R-008"],expected:{...expected("CONTROL","HIGH","資本重複配置","RESOURCE_INVARIANT_VIOLATION","DISCOVER"),resourceInvariant:false} },
];
