import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { createCaseNumber, maskUid, validateRebateActivation, verifyTurnstile } from "../lib/rebate-activation.ts";
import { STANDARD_REBATE_RATE, statusTransitions } from "../config/rebate-activation.ts";
import { sendActivationReceipt, sendCompletionEmail } from "../lib/rebate-email.ts";

function validForm(overrides = {}) { const form = new FormData(); const values = { exchange: "bybit", displayName: " 測試使用者 ", uid: " 211762922 ", contactEmail: " USER@Example.COM ", consent: "true", "cf-turnstile-response": "test-turnstile-token", ...overrides }; for (const [key, value] of Object.entries(values)) form.set(key, value); return form; }

test("三欄有效表單會正規化但 UID 維持字串", () => { const result = validateRebateActivation(validForm()); assert.equal(result.ok, true); if (result.ok) { assert.equal(result.data.displayName, "測試使用者"); assert.equal(result.data.uid, "211762922"); assert.equal(typeof result.data.uid, "string"); assert.equal(result.data.contactEmail, "user@example.com"); assert.deepEqual(Object.keys(result.data).filter((key) => ["registrationDate","accountScenario","kycStatus","preReviewCaseNumber"].includes(key)), []); } });
test("名稱、UID、Email 與同意均由 server validation 驗證", () => { assert.equal(validateRebateActivation(validForm({ displayName: " " })).ok, false); assert.equal(validateRebateActivation(validForm({ uid: "" })).ok, false); assert.equal(validateRebateActivation(validForm({ uid: "12.5x" })).ok, false); assert.equal(validateRebateActivation(validForm({ contactEmail: "invalid" })).ok, false); assert.equal(validateRebateActivation(validForm({ consent: "false" })).ok, false); });
test("Turnstile 失敗時拒絕申請", async () => { const old = process.env.TURNSTILE_SECRET_KEY; process.env.TURNSTILE_SECRET_KEY = "secret"; try { assert.equal(await verifyTurnstile("bad", null, async () => new Response('{"success":false}', { status: 200 })), false); } finally { if (old === undefined) delete process.env.TURNSTILE_SECRET_KEY; else process.env.TURNSTILE_SECRET_KEY = old; } });
test("案件編號使用安全隨機後綴且不重複", () => { const ids = new Set(Array.from({ length: 500 }, () => createCaseNumber("BB", new Date("2026-08-01T00:00:00Z")))); assert.equal(ids.size, 500); assert.match([...ids][0], /^BB-20260801-[A-Z0-9_-]{7}$/); });
test("一般案件比例固定 20 且完成狀態不可再轉換", () => { assert.equal(STANDARD_REBATE_RATE, 20); assert.deepEqual(statusTransitions.PENDING, ["COMPLETED","NEEDS_INFORMATION","NOT_FOUND","CANCELLED"]); assert.deepEqual(statusTransitions.COMPLETED, []); assert.ok(statusTransitions.NEEDS_INFORMATION.includes("PENDING")); assert.ok(statusTransitions.NOT_FOUND.includes("PENDING")); });
test("UID 遮蔽符合公開成功畫面", () => assert.equal(maskUid("211762922"), "21****22"));

test("收件與完成 Email 使用固定 20%、安全提醒及後台連結", async () => { const sent=[]; const oldKey=process.env.EMAIL_PROVIDER_API_KEY, oldFetch=globalThis.fetch; process.env.EMAIL_PROVIDER_API_KEY="test"; globalThis.fetch=async(_url,init)=>{sent.push(JSON.parse(init.body));return new Response("{}",{status:200})}; const now=new Date("2026-08-01T00:00:00Z"); const item={id:"id",caseNumber:"BB-20260801-ABCDE12",exchange:"bybit",displayName:"測試",uid:"211762922",normalizedUid:"211762922",contactEmail:"user@example.com",normalizedEmail:"user@example.com",status:"COMPLETED",rebateRate:20,completedAt:now,completedBy:"hello@bibeck.com",completionConfirmed:true,emailReceiptSentAt:now,completionEmailSentAt:null,notificationStatus:"PENDING",notificationError:null,publicMessage:null,adminNote:null,consentVersion:"v1",consentedAt:now,createdAt:now,updatedAt:now,source:"test",utmSource:null,utmMedium:null,utmCampaign:null}; try{await sendActivationReceipt(item);await sendCompletionEmail(item)}finally{globalThis.fetch=oldFetch;if(oldKey===undefined)delete process.env.EMAIL_PROVIDER_API_KEY;else process.env.EMAIL_PROVIDER_API_KEY=oldKey} assert.equal(sent.length,2); assert.match(sent[0].subject,/已收到您的 Bybit 返傭開通申請/); assert.match(sent[0].html,/不代表返傭已完成設定/); assert.match(sent[1].subject,/已完成設定/); assert.match(sent[1].html,/20%/); assert.match(sent[1].html,/bybackoffice\.com/); assert.match(sent[1].html,/不會要求/); });

test("schema、migration、管理路由與 Modal 符合 MVP", async () => { const [schema,migration,form,admin,actions,api,sitemap,validation]=await Promise.all([readFile(new URL("../db/schema.ts",import.meta.url),"utf8"),readFile(new URL("../drizzle/0001_bybit_activation_mvp.sql",import.meta.url),"utf8"),readFile(new URL("../components/RebateActivationForm.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/rebate-requests/page.tsx",import.meta.url),"utf8"),readFile(new URL("../components/AdminCaseActions.tsx",import.meta.url),"utf8"),readFile(new URL("../app/api/admin/rebate-requests/[id]/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/sitemap.ts",import.meta.url),"utf8"),readFile(new URL("../lib/rebate-activation.ts",import.meta.url),"utf8")]); assert.match(schema,/rebateRate/); assert.match(schema,/completionConfirmed/); assert.match(schema,/completionEmailSentAt/); assert.match(schema,/rebate_activation_uid_unique/); assert.match(migration,/CHECK \("rebate_rate" = 20\)/); assert.doesNotMatch(form,/approvedRate|preReview|type="file"/); assert.match(validation,/from "zod"/); assert.match(validation,/activationSchema\.safeParse/); assert.match(admin,/requireAdmin/); assert.match(admin,/名稱、UID 或 Email/); assert.match(admin,/CopyButton value=\{item\.uid\}/); assert.match(admin,/CopyButton value=\{item\.contactEmail\}/); assert.match(actions,/role="dialog"/); assert.match(actions,/確認並寄送通知/); assert.match(actions,/completionConfirmed/); assert.match(actions,/statusTransitions\[status\]/); assert.match(api,/retryNotification/); assert.match(api,/sendCompletionEmail/); assert.doesNotMatch(sitemap,/rebate\/activate|admin\/rebate/); });

test("公開案件狀態頁已移除且 CTA 永遠連到開通頁", async () => { const [actions,platform,contact]=await Promise.all([readFile(new URL("../components/ExchangeActionButtons.tsx",import.meta.url),"utf8"),readFile(new URL("../components/ExchangePlatformPage.tsx",import.meta.url),"utf8"),readFile(new URL("../app/contact/page.tsx",import.meta.url),"utf8")]); for (const source of [actions,platform]) { assert.match(source,/已完成註冊，繼續開通返傭/); assert.match(source,/href="\/rebate\/activate"/); } assert.match(contact,/繼續開通 Bybit 返傭/); assert.doesNotMatch(actions,/功能準備中|rebateActivationReadiness/); assert.doesNotMatch(platform,/功能準備中|rebateActivationReadiness/); assert.doesNotMatch(contact,/開通功能準備中|rebateActivationReadiness/); await assert.rejects(readFile(new URL("../app/rebate/status/[token]/page.tsx",import.meta.url),"utf8")); });
