import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render(pathname="/") { const workerUrl=new URL("../dist/server/index.js",import.meta.url); workerUrl.searchParams.set("test",process.pid+Date.now()+pathname); const {default:worker}=await import(workerUrl.href); return worker.fetch(new Request("http://localhost"+pathname,{headers:{accept:"text/html"}}),{ASSETS:{fetch:async()=>new Response("Not found",{status:404})}},{waitUntil(){},passThroughOnException(){}}); }

test("首頁以 35% 具體返傭價值與 Quick Calculator 為核心",async()=>{const html=await (await render()).text(); for(const text of ["把你付出去的手續費，拿回","1,000 USDT","350 USDT","算算我能拿回多少","降低每一筆交易成本"]) assert.match(html,new RegExp(text)); assert.doesNotMatch(html,/40%|400 USDT/);});
test("Bybit 頁定位為資料中心且不重複完整計算器",async()=>{const html=await (await render("/platform/bybit")).text(); for(const text of ["標準 35% 返傭與 Trader Status","Member","Pro","Black","Partner","取得 35% 返傭帳戶","登入 Bybit 返傭後台","使用你的交易量計算 Bybit 實際成本"]) assert.match(html,new RegExp(text)); assert.doesNotMatch(html,/40%|公開返傭級距/);});
test("FAQ schema 含 35% 金額與計算基礎說明",async()=>{const html=await (await render("/faq")).text(); assert.match(html,/FAQPage/); for(const text of ["BiBeck 標準返傭是多少","如果我產生 1,000 USDT 的交易手續費，可以返多少","35% 是從交易量直接計算嗎","BiBeck 的 35% 代表總交易成本一定降低 35% 嗎"]) assert.match(html,new RegExp(text)); assert.doesNotMatch(html,/40%/);});
test("舊高交易量與啟用頁會重新導向",async()=>{for(const path of ["/high-volume-application","/rebate/activate"]){const response=await render(path); assert.ok([301,307,308].includes(response.status)); assert.match(response.headers.get("location")??"",/\/rebate$/);}});
test("共享比較矩陣、水平成本條與進度條設定存在",async()=>{const [source,rows,styles]=await Promise.all([readFile(new URL("../components/BybitCostCalculator.tsx",import.meta.url),"utf8"),readFile(new URL("../config/comparison-rows.ts",import.meta.url),"utf8"),readFile(new URL("../app/globals.css",import.meta.url),"utf8")]); assert.match(source,/aria-label="交易成本方案比較"/); assert.match(source,/data-comparison-row/); assert.match(source,/aria-label="30 日實際交易成本比較"/); assert.match(source,/aria-label={label}/); assert.doesNotMatch(source,/TradingCostChart/); assert.doesNotMatch(rows,/30 日交易量|30 日原始手續費/); assert.equal((rows.match(/key:/g)??[]).length,13); assert.match(styles,/comparison-matrix-row\s*\{\s*display:\s*contents/); assert.match(styles,/grid-auto-flow:\s*column/); assert.match(styles,/cost-bar-track/); assert.match(styles,/@media \(max-width: 767px\)[\s\S]*\.comparison-matrix\s*\{\s*display:none/);});
test("申請、後台與客服資料由環境變數集中管理",async()=>{const [links,env]=await Promise.all([readFile(new URL("../config/links.ts",import.meta.url),"utf8"),readFile(new URL("../.env.example",import.meta.url),"utf8")]); assert.match(links,/NEXT_PUBLIC_BIBECK_REBATE_APPLICATION_URL/); assert.match(links,/NEXT_PUBLIC_REBATE_BACKOFFICE_URL/); assert.match(links,/NEXT_PUBLIC_SUPPORT_EMAIL/); assert.match(env,/NEXT_PUBLIC_SUPPORT_EMAIL=support@bibeck.com/);});
