import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render(pathname="/") { const workerUrl=new URL("../dist/server/index.js",import.meta.url); workerUrl.searchParams.set("test",process.pid+Date.now()+pathname); const {default:worker}=await import(workerUrl.href); return worker.fetch(new Request("http://localhost"+pathname,{headers:{accept:"text/html"}}),{ASSETS:{fetch:async()=>new Response("Not found",{status:404})}},{waitUntil(){},passThroughOnException(){}}); }

test("首頁以 Quick Calculator 與 40% 標準返傭為核心",async()=>{const html=await (await render()).text(); for(const text of ["降低每一筆交易成本","免費計算交易成本","了解 40% 返傭","BiBeck 標準返傭就是 40%","查看完整成本分析"]) assert.match(html,new RegExp(text)); assert.doesNotMatch(html,/公開返傭級距|每月第一個星期二/);});
test("Bybit 頁定位為資料中心且不重複完整計算器",async()=>{const html=await (await render("/platform/bybit")).text(); for(const text of ["標準 40% 返傭與 Trader Status","Member","Pro","Black","Partner","取得 Bybit 返傭帳號","登入 Bybit 返傭後台","使用你的交易量計算 Bybit 實際成本"]) assert.match(html,new RegExp(text)); assert.doesNotMatch(html,/標準交易者|戰略交易者|公開返傭級距/);});
test("FAQ schema 與二十六項新制度問題一致",async()=>{const html=await (await render("/faq")).text(); assert.match(html,/FAQPage/); for(const text of ["BiBeck 標準返傭是多少","Trader Status 會改變 40% 標準返傭嗎","達到 Pro 或 Black 後會自動升級嗎","KYC 身分轉移是什麼"]) assert.match(html,new RegExp(text)); assert.doesNotMatch(html,/20%～40%|級距調整何時生效/);});
test("舊高交易量與啟用頁會重新導向",async()=>{for(const path of ["/high-volume-application","/rebate/activate"]){const response=await render(path); assert.ok([301,307,308].includes(response.status)); assert.match(response.headers.get("location")??"",/\/rebate$/);}});
test("共享比較矩陣、水平成本條與進度條設定存在",async()=>{const [source,rows,styles]=await Promise.all([readFile(new URL("../components/BybitCostCalculator.tsx",import.meta.url),"utf8"),readFile(new URL("../config/comparison-rows.ts",import.meta.url),"utf8"),readFile(new URL("../app/globals.css",import.meta.url),"utf8")]); assert.match(source,/aria-label="交易成本方案比較"/); assert.match(source,/data-comparison-row/); assert.match(source,/aria-label="30 日實際交易成本比較"/); assert.match(source,/aria-label={label}/); assert.doesNotMatch(source,/TradingCostChart/); assert.doesNotMatch(rows,/30 日交易量|30 日原始手續費/); assert.equal((rows.match(/key:/g)??[]).length,13); assert.match(styles,/comparison-matrix-row\s*\{\s*display:\s*contents/); assert.match(styles,/grid-auto-flow:\s*column/); assert.match(styles,/cost-bar-track/); assert.match(styles,/@media \(max-width: 767px\)[\s\S]*\.comparison-matrix\s*\{\s*display:none/);});
test("申請、後台與客服資料由環境變數集中管理",async()=>{const [links,env]=await Promise.all([readFile(new URL("../config/links.ts",import.meta.url),"utf8"),readFile(new URL("../.env.example",import.meta.url),"utf8")]); assert.match(links,/NEXT_PUBLIC_BIBECK_REBATE_APPLICATION_URL/); assert.match(links,/NEXT_PUBLIC_REBATE_BACKOFFICE_URL/); assert.match(links,/NEXT_PUBLIC_SUPPORT_EMAIL/); assert.match(env,/NEXT_PUBLIC_SUPPORT_EMAIL=support@bibeck.com/);});
