import type { Condition, ExecutableDecisionRule, RuleEffect, SemanticRef, ValueRef } from "../contracts/index.ts";
const literal = (value:string|number|boolean|null) => ({kind:"literal" as const,value});
const eq = (left:ValueRef,value:string|number|boolean|null):Condition => ({kind:"comparison",left,operator:"EQ",right:literal(value)});
const effect = (code:string,stage:RuleEffect["stageCandidate"]|undefined,severity:RuleEffect["severityCandidate"],quest?:string):RuleEffect => ({ findings:[{code,params:{}}],flags:[code],bottleneckCandidate:{code,params:{}},stageCandidate:stage,severityCandidate:severity,mainQuestCandidate:quest?{code:quest,params:{}}:undefined,sideMissionCandidates:[],blockers:[],missingInformation:[] });
const refs = (condition:Condition):ValueRef[] => condition.kind==="comparison"?[condition.left,...(condition.right.kind==="ref"?[condition.right.ref]:[])]:condition.kind==="logical"?condition.conditions.flatMap(refs):condition.kind==="not"?refs(condition.condition):[condition.ref];
const executable = (rule:Omit<ExecutableDecisionRule,"version"|"requiredKnownInputs">):ExecutableDecisionRule => ({...rule,version:"1.1.0",requiredKnownInputs:rule.result.mainQuestCandidate?.code.startsWith("DISCOVER")||rule.id==="R-015"?[]:[...new Set(refs(rule.condition))]});

export const executableRules:ExecutableDecisionRule[] = [
  executable({id:"R-008",phase:"DATA_QUALITY",order:0,condition:eq("flags.hasCapitalAssignmentConflict",true),result:{...effect("CAPITAL_ASSIGNMENT_CONFLICT",undefined,"HIGH"),blockers:[{code:"RESOURCE_INVARIANT_VIOLATION",params:{}}]},overrideBehavior:"CRITICAL_HALT",mergeBehavior:"PRIMARY_CANDIDATE",confidence:"HIGH",evidenceIds:["EV-001"],assumptionIds:[],enabled:true}),
  executable({id:"R-001",phase:"DATA_QUALITY",order:10,condition:eq("flags.hasMissingCriticalData",true),result:{...effect("MISSING_CRITICAL_DATA","STABILITY","MEDIUM","DISCOVER_MISSING_INFORMATION"),missingInformation:[{code:"REQUIRED_FINANCIAL_DATA",params:{}}]},overrideBehavior:"NONE",mergeBehavior:"PRIMARY_CANDIDATE",confidence:"HIGH",evidenceIds:["EV-004"],assumptionIds:[],enabled:true}),
  executable({id:"R-015",phase:"DATA_QUALITY",order:20,condition:eq("flags.hasCashFlowContradiction",true),result:{...effect("CASH_FLOW_CONTRADICTION","STABILITY","MEDIUM","RECONCILE_CASH_FLOW_INPUTS"),missingInformation:[{code:"RECONCILED_MONTHLY_SAVINGS",params:{}}]},blockedInputRefs:["flags.hasNegativeCoreCashFlow","flags.hasImmediateFundingGap","flags.hasMinimumViableLiquidityGap","flags.hasGoalConflict"],overrideBehavior:"BLOCK_DOWNSTREAM",mergeBehavior:"PRIMARY_CANDIDATE",confidence:"HIGH",evidenceIds:["EV-003","EV-004"],assumptionIds:[],enabled:true}),
  executable({id:"R-002",phase:"CRITICAL",order:10,condition:eq("flags.hasDelinquentDebt",true),result:effect("DELINQUENT_DEBT","SURVIVAL","CRITICAL","RESOLVE_DELINQUENCY"),overrideBehavior:"OVERRIDE_STAGE",mergeBehavior:"PRIMARY_CANDIDATE",confidence:"HIGH",evidenceIds:[],assumptionIds:["AS-002","AS-003"],enabled:true}),
  executable({id:"R-003",phase:"SURVIVAL",order:10,condition:eq("flags.hasNegativeCoreCashFlow",true),result:effect("NEGATIVE_CORE_CASH_FLOW","SURVIVAL","CRITICAL","REPAIR_CORE_CASH_FLOW"),overrideBehavior:"OVERRIDE_STAGE",mergeBehavior:"PRIMARY_CANDIDATE",confidence:"HIGH",evidenceIds:["EV-003"],assumptionIds:[],enabled:true}),
  executable({id:"R-004",phase:"SURVIVAL",order:20,condition:eq("flags.hasImmediateFundingGap",true),result:effect("IMMEDIATE_FUNDING_GAP","SURVIVAL","HIGH","CLOSE_IMMEDIATE_FUNDING_GAP"),overrideBehavior:"OVERRIDE_STAGE",mergeBehavior:"PRIMARY_CANDIDATE",confidence:"HIGH",evidenceIds:["EV-002"],assumptionIds:["AS-003"],enabled:true}),
  executable({id:"R-007",phase:"LIQUIDITY",order:5,condition:eq("flags.hasReservedCapital",true),result:{...effect("RESERVED_CAPITAL_EXCLUDED","STABILITY","MEDIUM"),bottleneckCandidate:undefined},overrideBehavior:"NONE",mergeBehavior:"SIDE_FINDING",confidence:"HIGH",evidenceIds:["EV-002"],assumptionIds:[],enabled:true}),
  executable({id:"R-005",phase:"LIQUIDITY",order:10,condition:{kind:"logical",operator:"AND",conditions:[eq("flags.hasHighCostDebt",true),eq("flags.hasUnknownDebtCost",false),eq("flags.hasMinimumViableLiquidityGap",true),{kind:"exists",ref:"config.minimumViableLiquidityMonths"}]},result:effect("MINIMUM_LIQUIDITY_GAP","STABILITY","HIGH","BUILD_MINIMUM_LIQUIDITY"),overrideBehavior:"OVERRIDE_MAIN_QUEST",mergeBehavior:"PRIMARY_CANDIDATE",confidence:"LOW",evidenceIds:[],assumptionIds:["AS-001","AS-004"],enabled:true}),
  executable({id:"R-006",phase:"CONTROL",order:10,condition:{kind:"logical",operator:"AND",conditions:[eq("flags.hasHighCostDebt",true),eq("flags.hasMinimumViableLiquidityGap",false),eq("flags.hasUnknownDebtCost",false)]},discoveryCondition:eq("flags.hasUnknownDebtCost",true),discoveryResult:{...effect("NEED_MORE_INFORMATION","CONTROL","MEDIUM","CONFIRM_DEBT_COST"),missingInformation:[{code:"DEBT_COST_CLASSIFICATION",params:{}}]},result:effect("HIGH_COST_DEBT","CONTROL","HIGH","REDUCE_HIGH_COST_DEBT"),overrideBehavior:"NONE",mergeBehavior:"PRIMARY_CANDIDATE",confidence:"LOW",evidenceIds:[],assumptionIds:["AS-004"],enabled:true}),
  executable({id:"R-011",phase:"CONTROL",order:20,condition:eq("flags.hasAllocationConflict",true),result:effect("ALLOCATION_CONFLICT","CONTROL","MEDIUM","DECIDE_ALLOCATION_TRADEOFF"),overrideBehavior:"NONE",mergeBehavior:"PRIMARY_CANDIDATE",confidence:"MEDIUM",evidenceIds:["EV-007"],assumptionIds:[],enabled:true}),
  executable({id:"R-012",phase:"CONTROL",order:30,condition:{kind:"logical",operator:"AND",conditions:[eq("flags.hasNegativeNetWorth",true),eq("flags.hasDelinquentDebt",false),eq("flags.hasNegativeCoreCashFlow",false)]},result:{...effect("NEGATIVE_NET_WORTH_CONTEXT","CONTROL","LOW"),bottleneckCandidate:undefined},overrideBehavior:"NONE",mergeBehavior:"SIDE_FINDING",confidence:"HIGH",evidenceIds:["EV-005"],assumptionIds:["AS-007"],enabled:true}),
  executable({id:"R-013",phase:"CONTROL",order:40,condition:eq("flags.hasZeroIncome",true),result:{...effect("ZERO_INCOME_REQUIRES_RESOURCE_COVERAGE","STABILITY","MEDIUM"),bottleneckCandidate:undefined,sideMissionCandidates:[{code:"EVALUATE_RESOURCE_RUNWAY",params:{}}]},overrideBehavior:"NONE",mergeBehavior:"SIDE_FINDING",confidence:"HIGH",evidenceIds:["EV-006"],assumptionIds:[],enabled:true}),
  executable({id:"R-010",phase:"GOAL_CONFLICT",order:10,condition:eq("flags.hasGoalConflict",true),result:effect("GOAL_FUNDING_CONFLICT","ACCUMULATION","MEDIUM","DECIDE_GOAL_PRIORITY"),overrideBehavior:"NONE",mergeBehavior:"PRIMARY_CANDIDATE",confidence:"MEDIUM",evidenceIds:["EV-004"],assumptionIds:["AS-003"],enabled:true}),
  executable({id:"R-009",phase:"ACCUMULATION",order:10,condition:eq("flags.hasGoalFundingClaim",true),result:{...effect("GOAL_FUNDING_REDUCES_INVESTABLE_CAPITAL","ACCUMULATION","MEDIUM"),bottleneckCandidate:undefined},overrideBehavior:"NONE",mergeBehavior:"SIDE_FINDING",confidence:"MEDIUM",evidenceIds:["EV-007"],assumptionIds:["AS-003"],enabled:true}),
  executable({id:"R-014",phase:"OPTIMIZATION",order:100,condition:{kind:"logical",operator:"AND",conditions:[eq("counts.unresolvedPriorityClaims",0),eq("flags.hasUnresolvedPriorityClaim",false),eq("flags.hasMissingCriticalData",false)]},result:{findings:[{code:"NO_UNRESOLVED_PRIORITY_CLAIM",params:{}}],flags:["NO_FORCED_MISSION"],bottleneckCandidate:{code:"NO_UNRESOLVED_PRIORITY_CLAIM",params:{}},severityCandidate:"NONE",mainQuestCandidate:undefined,sideMissionCandidates:[],blockers:[],missingInformation:[]},overrideBehavior:"NONE",mergeBehavior:"NO_MISSION",confidence:"HIGH",evidenceIds:[],assumptionIds:["AS-005","AS-006","AS-008"],enabled:true}),
];

export const semantic = (code:string,params:SemanticRef["params"]={}):SemanticRef => ({code,params});
