export type UnknownHandling = "PROPAGATE_UNKNOWN" | "EMIT_INFORMATION_GAP" | "USE_EXPLICIT_ASSUMPTION_CONFIG";
export interface ModelCalculationContract { modelId:string; inputs:string[]; derivedValues:string[]; calculationSemantics:string[]; unknownHandling:UnknownHandling[]; outputs:string[]; executableReference:string|null; unresolved:string[] }
export const modelCalculationContracts:ModelCalculationContract[]=[
  {modelId:"cash_flow_v1",inputs:["income[].averageMonthlyNetIncome","expenses.necessaryMonthly","expenses.discretionaryMonthly","liabilities[].minimumMonthlyPayment","expenses.otherMonthlyRequired"],derivedValues:["metrics.netMonthlyIncome","metrics.coreMonthlyOutflow","metrics.coreCashFlow","metrics.monthlySurplus"],calculationSemantics:["NetMonthlyIncome = sum known monthly net income","CoreMonthlyOutflow = sum unique approved monthly economic payments from expenses, debt minimums and required recurring obligations","CoreCashFlow = usable monthly income - CoreMonthlyOutflow","MonthlySurplus = NetMonthlyIncome - necessary - discretionary - debt minimums - other required"],unknownHandling:["PROPAGATE_UNKNOWN","EMIT_INFORMATION_GAP"],outputs:["cash-flow metrics","cash-flow contradiction flag"],executableReference:"reference/profile-normalizer.ts",unresolved:["irregular and seasonal income normalization","annual expense periodization"]},
  {modelId:"liquidity_v1",inputs:["FinancialResource[]","CapitalAssignment[]","Obligation[]","metrics.coreMonthlyOutflow","config.minimumViableLiquidityMonths"],derivedValues:["metrics.availableSafetyLiquidity30d","metrics.availableSafetyLiquidity90d","metrics.availableSafetyLiquidity365d","metrics.financialRunwayMonths"],calculationSemantics:["exclude reserved/restricted/locked/unsettled resources","subtract unique reservations and uncovered dated required obligation occurrences once by horizon","FinancialRunwayMonths = available safety liquidity / core monthly outflow when denominator is known and positive"],unknownHandling:["PROPAGATE_UNKNOWN","USE_EXPLICIT_ASSUMPTION_CONFIG"],outputs:["liquidity metrics","funding-gap flags"],executableReference:"reference/profile-normalizer.ts",unresolved:["dynamic safety target","liquid-investment and crypto haircut","settlement treatment"]},
  {modelId:"debt_priority_v1",inputs:["Liability[]","liquidity outputs","jurisdictional debt classification"],derivedValues:["flags.hasDelinquentDebt","flags.hasUnknownDebtCost","flags.hasHighCostDebt"],calculationSemantics:["delinquency is evaluated before acceleration","high-cost classification must be supplied by versioned jurisdiction configuration","reference emits only independently known delinquency and explicitly supplied cost state; full acceleration policy is not implemented"],unknownHandling:["PROPAGATE_UNKNOWN","EMIT_INFORMATION_GAP"],outputs:["debt flags","debt claim candidates"],executableReference:"reference/profile-normalizer.ts",unresolved:["high-cost threshold by jurisdiction","effective cost for promotional and variable rates","prepayment penalty and post-payment liquidity policy"]},
  {modelId:"goal_funding_v1",inputs:["Goal[]","CapitalAssignment[]","sustainable contribution input"],derivedValues:["metrics.sustainableGoalCapital","metrics.totalGoalClaims","flags.hasGoalConflict"],calculationSemantics:["required and user priority remain separate","unknown amount or deadline emits information gap","goal capital shares underlying asset lineage","totalGoalClaims is the validated complete sum of active goal target minus funded amount; sustainability/conflict stays UNKNOWN"],unknownHandling:["PROPAGATE_UNKNOWN","EMIT_INFORMATION_GAP"],outputs:["goal claims","goal-conflict flag"],executableReference:"reference/profile-normalizer.ts",unresolved:["goal feasibility model","changing contribution capacity"]},
  {modelId:"investable_capital_v1",inputs:["sustainable allocatable capital","higher-priority claims"],derivedValues:["metrics.longTermInvestableCapital"],calculationSemantics:["LongTermInvestableCapital = max(SustainableAllocatableCapital - HigherPriorityCapitalClaims, 0)","the same capital cannot fund a goal and long-term investing"],unknownHandling:["PROPAGATE_UNKNOWN"],outputs:["potential investable capital","goal displacement consequence"],executableReference:null,unresolved:["sustainable allocatable capital derivation","risk capacity","asset allocation"]},
  {modelId:"bottleneck_v1",inputs:["NormalizedDecisionContext","ExecutableDecisionRule[]"],derivedValues:["matched rule evaluations","primary bottleneck","stage","severity"],calculationSemantics:["phase then order then rule ID lexical ordering","override behavior is explicit","severity resolves independently from stage"],unknownHandling:["PROPAGATE_UNKNOWN","EMIT_INFORMATION_GAP"],outputs:["ReferenceDecisionOutput"],executableReference:"reference/reference-evaluator.ts",unresolved:[]},
  {modelId:"mission_v1",inputs:["semantic bottleneck","rule mission candidates"],derivedValues:["main mission semantic ref","side mission semantic refs"],calculationSemantics:["at most one main mission","zero to three side missions","subjective decisions cannot be externally verified","financial actions require only their declared known dependencies; independent supported actions survive discovery"],unknownHandling:["EMIT_INFORMATION_GAP"],outputs:["Mission semantic contracts"],executableReference:"reference/reference-evaluator.ts",unresolved:["copy rendering belongs to localization layer"]},
];
