import type { DecisionRule } from "../contracts/index.ts";

const rule = (value: DecisionRule): DecisionRule => value;
export const rules: DecisionRule[] = [
  rule({ id:"R-001",name:"Missing critical data",purpose:"資料不足時阻止假精確配置。",requiredInputs:["requiredProfileFields"],conditions:["critical input is UNKNOWN"],priorityClass:"P0_HARD",result:"NEED_MORE_INFORMATION",stageImpact:"STABILITY",severityImpact:"MEDIUM",mainQuestCandidate:"DISCOVER",sideMissionCandidates:[],evidenceIds:["EV-004"],assumptionIds:[],confidence:"HIGH",jurisdiction:["GENERAL"],version:"1.0",status:"WORKING",priorityChanging:true,tests:["CASE-006","CASE-010","CASE-013","CASE-019","CASE-022","ADV-010","ADV-014"] }),
  rule({ id:"R-002",name:"Delinquency precedence",purpose:"重大逾期與必要義務優先於最佳化。",requiredInputs:["liabilities","obligations"],conditions:["delinquency is DELINQUENT or DEFAULT"],priorityClass:"P0_HARD",result:"RESOLVE_DELINQUENCY",stageImpact:"SURVIVAL",severityImpact:"CRITICAL",mainQuestCandidate:"REPAIR",sideMissionCandidates:["DISCOVER"],evidenceIds:[],assumptionIds:["AS-002","AS-003"],confidence:"HIGH",jurisdiction:["GENERAL"],version:"1.0",status:"WORKING",priorityChanging:true,tests:["CASE-003","COLLISION-001"] }),
  rule({ id:"R-003",name:"Core cash-flow failure",purpose:"辨識核心流出高於可用收入。",requiredInputs:["netMonthlyIncome","coreMonthlyOutflow"],conditions:["coreCashFlow < 0"],priorityClass:"P0_HARD",result:"NEGATIVE_CORE_CASH_FLOW",stageImpact:"SURVIVAL",severityImpact:"CRITICAL",mainQuestCandidate:"REPAIR",sideMissionCandidates:["DISCOVER"],evidenceIds:["EV-003"],assumptionIds:[],confidence:"HIGH",jurisdiction:["GENERAL"],version:"1.0",status:"WORKING",priorityChanging:true,tests:["CASE-001","COLLISION-001","ADV-012","ADV-014"] }),
  rule({ id:"R-004",name:"Near-term funding gap",purpose:"先處理 30 日必要義務缺口。",requiredInputs:["availableSafetyLiquidity30d","requiredObligations30d"],conditions:["availableSafetyLiquidity30d < requiredObligations30d"],priorityClass:"P0_HARD",result:"IMMEDIATE_FUNDING_GAP",stageImpact:"SURVIVAL",severityImpact:"HIGH",mainQuestCandidate:"BUILD",sideMissionCandidates:["DECIDE"],evidenceIds:["EV-002"],assumptionIds:["AS-003"],confidence:"HIGH",jurisdiction:["GENERAL"],version:"1.0",status:"WORKING",priorityChanging:true,tests:["CASE-002","CASE-004","ADV-011"] }),
  rule({ id:"R-005",name:"Minimum liquidity before debt acceleration",purpose:"最低可行流動性不足時維持最低還款並先建立流動性。",requiredInputs:["minimumViableLiquidity","availableSafetyLiquidity","debtMinimums"],conditions:["high-cost debt exists","available safety liquidity below working milestone"],priorityClass:"P1_PROTECTIVE",result:"BUILD_MINIMUM_LIQUIDITY",stageImpact:"STABILITY",severityImpact:"HIGH",mainQuestCandidate:"BUILD",sideMissionCandidates:["REPAIR"],evidenceIds:[],assumptionIds:["AS-001","AS-004"],confidence:"LOW",jurisdiction:["GENERAL","TW"],version:"1.0",status:"RESEARCH_REQUIRED",priorityChanging:true,tests:["CASE-008","COLLISION-002","ADV-009","ADV-011"] }),
  rule({ id:"R-006",name:"High-cost debt after minimum liquidity",purpose:"達工作流動性里程碑後，保留該流動性並優先處理已由司法管轄模型分類的高成本債務。",requiredInputs:["debtCostClassification","minimumViableLiquidity","prepaymentPenalty"],conditions:["high-cost debt classification is known","minimum viable liquidity is met"],priorityClass:"P1_PROTECTIVE",result:"DEBT_PRIORITY",stageImpact:"CONTROL",severityImpact:"HIGH",mainQuestCandidate:"REPAIR",sideMissionCandidates:[],evidenceIds:[],assumptionIds:["AS-004"],confidence:"LOW",jurisdiction:["GENERAL","TW"],version:"1.0",status:"RESEARCH_REQUIRED",priorityChanging:true,tests:["CASE-007","COLLISION-002","ADV-008","ADV-009"] }),
  rule({ id:"R-007",name:"Reserved capital exclusion",purpose:"從安全流動性排除已保留資本。",requiredInputs:["assets","obligations","goals"],conditions:["capital assignment is reserved"],priorityClass:"P1_PROTECTIVE",result:"EXCLUDE_RESERVED_CAPITAL",stageImpact:"STABILITY",severityImpact:"MEDIUM",mainQuestCandidate:null,sideMissionCandidates:[],evidenceIds:["EV-002"],assumptionIds:[],confidence:"HIGH",jurisdiction:["GENERAL"],version:"1.0",status:"WORKING",priorityChanging:true,tests:["CASE-005"] }),
  rule({ id:"R-008",name:"No double assignment",purpose:"防止資源超額或重複配置。",requiredInputs:["resources","allocations"],conditions:["allocation exceeds resource or assignment is duplicated"],priorityClass:"P0_HARD",result:"RESOURCE_INVARIANT_VIOLATION",stageImpact:"CONTROL",severityImpact:"HIGH",mainQuestCandidate:"DISCOVER",sideMissionCandidates:[],evidenceIds:["EV-001"],assumptionIds:[],confidence:"HIGH",jurisdiction:["GENERAL"],version:"1.0",status:"WORKING",priorityChanging:true,tests:["CASE-024","ADV-001","ADV-002","ADV-003","ADV-004"] }),
  rule({ id:"R-009",name:"Goal funding competes with investing",purpose:"必要目標資金不得同時算作長期可投資資本。",requiredInputs:["goalClaims","sustainableAllocatableCapital"],conditions:["goal claim consumes available capital"],priorityClass:"P2_CHOSEN",result:"REDUCE_LONG_TERM_INVESTABLE_CAPITAL",stageImpact:"ACCUMULATION",severityImpact:"MEDIUM",mainQuestCandidate:"DECIDE",sideMissionCandidates:[],evidenceIds:["EV-007"],assumptionIds:["AS-003"],confidence:"MEDIUM",jurisdiction:["GENERAL"],version:"1.0",status:"WORKING",priorityChanging:true,tests:["CASE-014","COLLISION-003"] }),
  rule({ id:"R-010",name:"Incompatible goal funding",purpose:"多項目標超過可持續目標資本時顯示衝突。",requiredInputs:["goalClaims","sustainableGoalCapital"],conditions:["total goal claims > sustainable goal capital"],priorityClass:"P2_CHOSEN",result:"FUNDING_CONFLICT",stageImpact:"ACCUMULATION",severityImpact:"MEDIUM",mainQuestCandidate:"DECIDE",sideMissionCandidates:[],evidenceIds:["EV-004"],assumptionIds:["AS-003"],confidence:"MEDIUM",jurisdiction:["GENERAL"],version:"1.0",status:"WORKING",priorityChanging:true,tests:["CASE-015","CASE-016","COLLISION-003"] }),
  rule({ id:"R-011",name:"Discretionary spending neutrality",purpose:"可支配消費不被自動視為錯誤，只在資源不足時顯示取捨。",requiredInputs:["discretionarySpending","higherPriorityClaims","availableResources"],conditions:["discretionary spending plus higher-priority claims exceeds resources"],priorityClass:"P2_CHOSEN",result:"ALLOCATION_CONFLICT",stageImpact:"CONTROL",severityImpact:"MEDIUM",mainQuestCandidate:"DECIDE",sideMissionCandidates:[],evidenceIds:["EV-007"],assumptionIds:[],confidence:"MEDIUM",jurisdiction:["GENERAL"],version:"1.0",status:"WORKING",priorityChanging:true,tests:["CASE-011","COLLISION-004","ADV-015"] }),
  rule({ id:"R-012",name:"Net worth is not priority",purpose:"避免以負淨值單獨判定危急。",requiredInputs:["netWorth"],conditions:["netWorth < 0 and no higher-priority condition"],priorityClass:"P1_PROTECTIVE",result:"DO_NOT_ESCALATE_FROM_NET_WORTH_ALONE",stageImpact:"CONTROL",severityImpact:"LOW",mainQuestCandidate:null,sideMissionCandidates:[],evidenceIds:["EV-005"],assumptionIds:["AS-007"],confidence:"HIGH",jurisdiction:["GENERAL"],version:"1.0",status:"WORKING",priorityChanging:true,tests:["CASE-009","CASE-021"] }),
  rule({ id:"R-013",name:"Zero income requires context",purpose:"收入為零時依流動資源與義務判斷，不自動判定生存危機。",requiredInputs:["netMonthlyIncome","liquidResources","obligations"],conditions:["netMonthlyIncome = 0"],priorityClass:"P1_PROTECTIVE",result:"EVALUATE_RESOURCE_RUNWAY",stageImpact:"STABILITY",severityImpact:"MEDIUM",mainQuestCandidate:null,sideMissionCandidates:["DISCOVER"],evidenceIds:["EV-006"],assumptionIds:[],confidence:"HIGH",jurisdiction:["GENERAL"],version:"1.0",status:"WORKING",priorityChanging:true,tests:["CASE-020","ADV-007"] }),
  rule({ id:"R-014",name:"No unresolved claim means no mission",purpose:"健康狀態不製造假任務。",requiredInputs:["unresolvedPriorityClaims"],conditions:["unresolved priority claims = 0"],priorityClass:"P3_OPTIMIZATION",result:"NO_FORCED_MISSION",stageImpact:"OPTIONALITY",severityImpact:"NONE",mainQuestCandidate:null,sideMissionCandidates:[],evidenceIds:[],assumptionIds:["AS-005","AS-006","AS-008"],confidence:"HIGH",jurisdiction:["GENERAL"],version:"1.0",status:"WORKING",priorityChanging:false,tests:["CASE-012","CASE-017","CASE-018","ADV-015"] }),
  rule({ id:"R-015",name:"Cash-flow reconciliation",purpose:"回報儲蓄與計算剩餘矛盾時先要求核對。",requiredInputs:["reportedMonthlySavings","calculatedMonthlySurplus"],conditions:["material contradiction is present"],priorityClass:"P0_HARD",result:"NEED_MORE_INFORMATION",stageImpact:"STABILITY",severityImpact:"MEDIUM",mainQuestCandidate:"DISCOVER",sideMissionCandidates:[],evidenceIds:["EV-003","EV-004"],assumptionIds:[],confidence:"HIGH",jurisdiction:["GENERAL"],version:"1.0",status:"WORKING",priorityChanging:true,tests:["CASE-023"] }),
];
