import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SiteShell } from "@/components/SiteShell";
import { rebateStatusLabels } from "@/config/rebate-activation";
import { getCaseByTrackingToken } from "@/lib/rebate-case-store";
import { maskEmail, maskUid } from "@/lib/rebate-activation";

export const metadata: Metadata = { title: "返傭案件狀態｜BiBeck", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
const nextSteps = { SUBMITTED: "BiBeck 將確認 UID 是否可在後台查得。", UID_PENDING: "正在人工確認 UID 與推薦關係。", PENDING_MANUAL_SETUP: "UID 已確認，等待營運者在外部後台設定。", NEEDS_INFORMATION: "請依公開補件訊息聯絡 support@bibeck.com。", NOT_ATTRIBUTED: "目前無法確認指定推薦關係，請依說明聯絡客服。", COMPLETED: "人工設定已完成；實際同步與追溯仍以 Bybit 紀錄及規則為準。", CANCELLED: "案件已取消；如有疑問請聯絡客服。" } as const;
export default async function RebateStatusPage({ params }: { params: Promise<{ token: string }> }) { const { token } = await params; let caseData = null; try { caseData = await getCaseByTrackingToken(token); } catch { /* fail closed */ } if (!caseData) notFound(); const rows = [["案件編號", caseData.caseNumber], ["交易所", "Bybit"], ["UID", maskUid(caseData.uid)], ["聯絡 Email", maskEmail(caseData.contactEmail)], ["申請日期", caseData.createdAt.toLocaleString("zh-TW", { timeZone: "Asia/Taipei", hour12: false })], ["目前狀態", rebateStatusLabels[caseData.status]], ["最後更新", caseData.updatedAt.toLocaleString("zh-TW", { timeZone: "Asia/Taipei", hour12: false })]]; if (caseData.status === "COMPLETED" && caseData.approvedRate !== null) rows.push(["實際設定返傭比例", `${caseData.approvedRate}%`]); return <SiteShell><main className="px-5 pb-24 pt-36 sm:px-8 lg:pt-44"><div className="mx-auto max-w-3xl"><p className="eyebrow">申請進度</p><h1 className="mt-6 text-4xl font-semibold text-white sm:text-5xl">返傭案件狀態</h1><dl className="mt-10 divide-y divide-white/10 border-y border-white/10">{rows.map(([label, value]) => <div key={label} className="grid gap-2 py-5 sm:grid-cols-[12rem_1fr]"><dt className="text-sm text-secondary">{label}</dt><dd className="break-words text-white">{value}</dd></div>)}</dl><div className="mt-8 border-l-2 border-gold bg-[#121212] p-6"><h2 className="font-semibold text-white">下一步</h2><p className="mt-3 text-sm leading-7 text-secondary">{nextSteps[caseData.status]}</p>{caseData.publicMessage ? <p className="mt-3 text-sm leading-7 text-gold">{caseData.publicMessage}</p> : null}</div><p className="mt-6 text-xs leading-6 text-white/45">此頁只顯示遮蔽資料，不會顯示管理員內部備註。請勿轉寄案件查詢連結。</p></div></main></SiteShell>; }
