import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminCaseActions, CopyButton } from "@/components/AdminCaseActions";
import { rebateStatusLabels, type RebateActivationStatus } from "@/config/rebate-activation";
import { requireAdmin } from "@/lib/admin-auth";
import { getCaseWithEvents } from "@/lib/rebate-case-store";

export const metadata: Metadata = { title: "返傭開通案件｜BiBeck Operations", robots: { index: false, follow: false } }; export const dynamic = "force-dynamic";
export default async function AdminRequestDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; await requireAdmin(`/admin/rebate-requests/${id}`); let record = null; try { record = await getCaseWithEvents(id); } catch { /* database unavailable */ } if (!record) notFound(); const { caseData, events } = record; const status = caseData.status as RebateActivationStatus;
  const details = [["案件編號", caseData.caseNumber], ["名稱或稱呼", caseData.displayName], ["Bybit UID", caseData.uid], ["Email", caseData.contactEmail], ["返傭比例", "20%"], ["狀態", rebateStatusLabels[status]], ["完成時間", caseData.completedAt?.toISOString() || "—"], ["完成者", caseData.completedBy || "—"], ["完成確認", caseData.completionConfirmed ? "已確認" : "未確認"], ["公開說明", caseData.publicMessage || "—"], ["內部備註", caseData.adminNote || "—"]];
  return <main className="min-h-screen bg-[#0a0a0a] px-5 py-12 text-white"><div className="mx-auto max-w-6xl"><Link href="/admin/rebate-requests" className="text-link">返回申請清單</Link><div className="mt-6 grid gap-8 lg:grid-cols-[1fr_22rem]"><div><h1 className="text-3xl font-semibold">{caseData.caseNumber}</h1>{caseData.notificationStatus === "FAILED" ? <p className="mt-4 border border-red-400/30 bg-red-950/20 p-4 text-sm text-red-200">完成通知寄送失敗：{caseData.notificationError || "未知錯誤"}</p> : null}<dl className="mt-7 divide-y divide-white/10 border-y border-white/10">{details.map(([label, value]) => <div key={label as string} className="grid gap-2 py-4 sm:grid-cols-[10rem_1fr]"><dt className="text-sm text-secondary">{label}</dt><dd className="break-words">{value}{label === "Bybit UID" ? <span className="ml-3"><CopyButton value={caseData.uid} label=" UID" /></span> : null}{label === "Email" ? <span className="ml-3"><CopyButton value={caseData.contactEmail} label=" Email" /></span> : null}</dd></div>)}</dl><section className="mt-10"><h2 className="text-xl font-semibold">操作紀錄</h2><ol className="mt-5 divide-y divide-white/10 border-y border-white/10">{events.map((event) => <li key={event.id} className="py-4 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{event.eventType}</strong><time className="text-secondary">{event.createdAt.toLocaleString("zh-TW", { timeZone: "Asia/Taipei", hour12: false })}</time></div><p className="mt-2 text-secondary">{event.previousStatus || "—"} → {event.newStatus || "—"} · {event.actorEmail}</p>{event.publicMessage ? <p className="mt-1">公開：{event.publicMessage}</p> : null}{event.internalMessage ? <p className="mt-1 text-gold">內部：{event.internalMessage}</p> : null}</li>)}</ol></section></div><AdminCaseActions id={id} displayName={caseData.displayName} uid={caseData.uid} email={caseData.contactEmail} status={status} hasNotificationError={caseData.notificationStatus === "FAILED"} /></div></div></main>;
}
