import type { RebateActivationCase } from "../db/schema.ts";
import { rebateStatusLabels } from "../config/rebate-activation.ts";
import { emailLayout, sendTransactionalEmail } from "./email-provider.ts";
import { maskUid } from "./rebate-activation.ts";

const appUrl = () => (process.env.APP_URL || "https://bibeck.com").replace(/\/$/, "");
const safety = "BiBeck 不會要求您的交易所密碼、驗證碼、API Secret、私鑰或助記詞。";
export async function sendActivationReceived(caseData: RebateActivationCase, trackingToken: string) {
  const href = `${appUrl()}/rebate/status/${trackingToken}`;
  await sendTransactionalEmail({ to: caseData.contactEmail, subject: `[BiBeck] 已收到返傭啟用申請｜${caseData.caseNumber}`, idempotencyKey: `activation-received-${caseData.id}-${caseData.updatedAt.getTime()}`, html: emailLayout("已收到返傭啟用申請", ["此信僅代表 BiBeck 已收到申請，不代表返傭已完成設定。", "設定完成前，返傭是否生效及是否追溯，仍以 Bybit 規則及後台紀錄為準。", safety], [["稱呼", caseData.displayName], ["案件編號", caseData.caseNumber], ["交易所", "Bybit"], ["UID", maskUid(caseData.uid)], ["申請時間", caseData.createdAt.toISOString()], ["目前狀態", rebateStatusLabels[caseData.status]]], { label: "查看案件狀態", href }) });
}
export async function sendAdminNewCase(caseData: RebateActivationCase) { const to = process.env.REBATE_ADMIN_EMAIL; if (!to) throw new Error("REBATE_ADMIN_EMAIL_NOT_CONFIGURED"); await sendTransactionalEmail({ to, replyTo: caseData.contactEmail, subject: `[BiBeck 管理] 新返傭啟用案件｜${caseData.caseNumber}`, idempotencyKey: `activation-admin-${caseData.id}`, html: emailLayout("新返傭啟用案件", ["請登入 BiBeck 管理頁人工確認 UID 與推薦關係。"], [["案件編號", caseData.caseNumber], ["交易所", "Bybit"], ["UID", caseData.uid], ["稱呼", caseData.displayName]]) }); }
export async function sendActivationStatusEmail(caseData: RebateActivationCase, trackingToken: string, status: "NEEDS_INFORMATION" | "NOT_ATTRIBUTED" | "COMPLETED" | "CANCELLED") { const href = `${appUrl()}/rebate/status/${trackingToken}`; const completed = status === "COMPLETED"; const title = completed ? "返傭設定已完成" : rebateStatusLabels[status]; const paragraphs = completed ? ["此通知代表 BiBeck 已完成人工設定。實際生效時間、顯示同步及過往手續費是否追溯，仍以 Bybit 的系統紀錄與適用規則為準。", safety] : [caseData.publicMessage || "請開啟案件狀態頁查看最新說明。", safety]; const rows: [string, string][] = [["案件編號", caseData.caseNumber], ["交易所", "Bybit"], ["UID", maskUid(caseData.uid)], ["目前狀態", rebateStatusLabels[status]]]; if (completed) rows.push(["實際設定比例", `${caseData.approvedRate}%`], ["設定完成時間", (caseData.completedAt || caseData.updatedAt).toISOString()]); await sendTransactionalEmail({ to: caseData.contactEmail, subject: `[BiBeck] ${title}｜${caseData.caseNumber}`, idempotencyKey: `activation-status-${caseData.id}-${status}-${caseData.updatedAt.getTime()}`, html: emailLayout(title, paragraphs, rows, { label: "查看案件狀態", href }) }); }
